<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>CrystalCommand.Core</PackageId>
        <Description>Command framework for .NET</Description>
        <PackageTags>command;parser;framework</PackageTags>
    </PropertyGroup>

</Project>
