<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>CrystalCommand.Attribute</PackageId>
        <Description>Attribute support for CrystalCommand</Description>
        <PackageTags>command;attribute;framework</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrystalCommand.Core\CrystalCommand.Core.csproj" />
    </ItemGroup>

</Project>
