<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Attribute\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrystalCommand.Core\CrystalCommand.Core.csproj" />
    </ItemGroup>

</Project>
